### ISSUE TITLE
Hi, I noticed that the data set in ood.sh doesn't seem to be in the repository or Google drive either

### ISSUE THREAD

**Issue by REMEATGreens** [copenlu/weak-labeler#2]
for example:
'--training_path weaklabeler/Data/stance_data/stance_data.csv'

Could you please share the file🥺🥺🥺🥺🥺

**Comment by osoblanco** [comment]
Hi @shengdan320 I have added the complete folder under the provided link in README.md . Leaving the link here as well just in case. Hope this resolves all the problems.

https://drive.google.com/drive/folders/1jxqgiCGwzNkkRa9THN7vZH-nzJwjHVx1?usp=drive_link

**Comment by shengdan320** [comment]
really appreciate it

**Comment by REMEATGreens** [comment]
> Hi @shengdan320 I have added the complete folder under the provided link in README.md . Leaving the link here as well just in case. Hope this resolves all the problems.
> 
> https://drive.google.com/drive/folders/1jxqgiCGwzNkkRa9THN7vZH-nzJwjHVx1?usp=drive_link

really appreciate it
